### ISSUE TITLE
Drop Python 2 Checklist

### ISSUE THREAD

**Issue by whonore** [whonore/Coqtail#159]
Since Python 2 is almost a year past it's [end of life](https://devguide.python.org/devcycle/#end-of-life-branches) it's about time for Coqtail to drop support for it and make 3.5 or 3.6 the new minimum requirement. Technically 3.5 has reached its end of life also, and it's missing some [nice features](https://docs.python.org/3/whatsnew/3.6.html) from 3.6, but I want to first check if it's still commonly used by anything (e.g., what version does Ubuntu give you by default).

Things to change:
- Git
  + [x] Create a new branch for the Python 2 version
- Documentation
  + [x] Update `README` to reflect the new required Python version
  + [x] Link to the Python 2 branch
  + [x] Link to documentation to build Vim with a more recent Vim
  + [x] Remove deprecation warning from `coqtail.py:splash`
  + [x] Remove the `python3-distutils` requirement
- Tests
  + [x] Remove the `*-py27`, `lint-2` environments and the `mypy -2` check in `tox.ini`
  + [x] Remove`2.7` from `py_version` in `.github/workflows/ci.yaml`
- Code
  + [x] Remove `python` case in `coqtail/compat.vim`
  + [x] Remove `six.py`, and the exclude rules for it in `setup.cfg`
  + [x] Remove all `__future__` imports
  + [x] Remove all `u` string prefixes
  + [x] Remove explicit `object` subclassing
  + [x] Use simple `super()` calls
  + [x] Change all function type comments to function type annotations
  + [x] Remove `try-except` around `typing` imports
  + [x] Use `str` instead of `Text` in types
  + [x] Remove unnecessary `type: ignore` comments
  + [x] Use type aliases for large types like in `coqtail.py:get_goals`
  + [x] Use `pathlib` instead of `os.path` where possible
  + [x] Replace `socket.error` with `ConnectionError` in `coqtail.py:parse_msgs`
  + [x] Replace `ValueError` with `json.JSONDecodeError` in `coqtail.py:_recv`
  + [x] Consider using `concurrent.futures` or similar instead of raw threads in
        `coqtop.py:call`
  + [x] Assign types to the fields of the `namedtuple`s in `xmlInterface.py`
  + [ ] Consider using `enum.Enum` instead of raw strings for the python/coqtop
        types in `xmlInterface.py`
  + [x] Use `shutil.which` in `xmlInterface.py:launch`
  + [x] Remove the `distutils` import in `xmlInterface.py`
  + [x] Use `re.fullmatch` instead of `re.match` with `$` where possible
        (`xmlInterface.py:valid_module`)
  + [x] Remove `re.UNICODE` flag
  + [x] Use `yield from` in `xmlInterface.py:_parse_tagged_tokens`

If switching to 3.6:
- Code
  + [x] Replace `.format` with f-strings
  + [x] Change all variable type comments to variable type annotations
